// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ukolnicek.Data;

#nullable disable

namespace Ukolnicek.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250625121406_ZmenaDatumNaDateTime")]
    partial class ZmenaDatumNaDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ukolnicek.Models.Ukol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum");

                    b.Property<bool>("Hotovo")
                        .HasColumnType("boolean")
                        .HasColumnName("hotovo");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazev");

                    b.Property<bool>("Smazano")
                        .HasColumnType("boolean")
                        .HasColumnName("smazano");

                    b.HasKey("Id");

                    b.ToTable("vsechnyukoly");
                });
#pragma warning restore 612, 618
        }
    }
}
